name: Commit CI

on:
  push:
    branches: [feature/**]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -C debuginfo=0 -D warnings

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      is_draft: ${{ steps.check-commit.outputs.is_draft }}
    env:
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    steps:
      - name: Check if this commit is a draft
        id: check-commit
        run: echo "is_draft=${{ startsWith(env.COMMIT_MESSAGE, 'draft') }}" >> $GITHUB_ENV
      - name: Skip if this commit is a draft
        if: ${{ startsWith(env.COMMIT_MESSAGE, 'draft') }}
        run: |
          echo "This commit is a draft, skip the following steps."
      - name: Check if commit message is signed off by the author
        run: |
          if ! echo $COMMIT_MESSAGE | grep -q "Signed-off-by"; then
            echo "Commit message is not signed off by the author."
            exit 1
          fi

  cargo-clippy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, nightly]
    runs-on: ${{ matrix.os }}
    needs: check-commit-message
    if: ${{ needs.check-commit-message.outputs.is_draft == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - name: Run cargo-clippy for ${{ matrix.os }} with ${{ matrix.rust }}
        run: cargo run -p ci -- cargo-clippy

  cargo-format:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    needs: check-commit-message
    if: ${{ needs.check-commit-message.outputs.is_draft == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt
      - name: Run cargo-fmt for ${{ matrix.os }} with ${{ matrix.rust }}
        run: cargo run -p ci -- cargo-format

  typo:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    needs: check-commit-message
    if: ${{ needs.check-commit-message.outputs.is_draft == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: typos-cli
      - name: Run typo for ${{ matrix.os }} with ${{ matrix.rust }}
        run: cargo run -p ci -- typo

  check-documents:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    needs: check-commit-message
    if: ${{ needs.check-commit-message.outputs.is_draft == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Check documents for ${{ matrix.os }} with ${{ matrix.rust }}
        run: cargo run -p ci -- cargo-doc

  cargo-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly]
    runs-on: ${{ matrix.os }}
    needs:
      [check-commit-message, cargo-clippy, cargo-format, typo, check-documents]
    if: ${{ needs.check-commit-message.outputs.is_draft == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo-check for ${{ matrix.os }} with ${{ matrix.rust }}
        run: cargo run -p ci -- cargo-check

  cargo-mirai:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]
    runs-on: ${{ matrix.os }}
    needs: [check-commit-message, cargo-check]
    if: ${{ needs.check-commit-message.outputs.is_draft == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "latest"
      - uses: egor-tensin/setup-clang@v1
        with:
          version: "latest"
      - name: Verify cmake and clang installation
        run: cmake --version &&  clang --version
      - name: Check if mirai is installed
        id: check-mirai-installed
        run: |
          if [ -f ~/.cargo/bin/mirai ]; then
            echo "is_mirai_exists=true" >> $GITHUB_ENV
          else
            echo "is_mirai_exists=false" >> $GITHUB_ENV
          fi
      - name: Install mirai if needed
        if: ${{ steps.check-mirai-installed.outputs.is_mirai_exists == false }}
        run: |
          git clone https://github.com/endorlabs/MIRAI.git
          cd MIRAI
          cargo install --locked --path ./checker
          cd $GITHUB_WORKSPACE
      - name: Run mirai for ${{ matrix.os }} with ${{ matrix.rust }}
        run: cargo run -p ci -- cargo-mirai
